server:
  port: 5000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
endpoint:
  service2: http://service2-env.eba-jyawwrsn.us-east-1.elasticbeanstalk.com/get-state
  service3: http://service3-env.eba-vrvtmbaf.us-east-1.elasticbeanstalk.com/post-state

